# Generated by Django 5.2 on 2025-05-25 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_remove_topic_content_topic_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='is_completed',
            new_name='topiccomplete',
        ),
    ]
