# Generated by Django 5.2.1 on 2025-05-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_rename_is_completed_topic_topiccomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_images/'),
        ),
    ]
