# Generated by Django 5.2.1 on 2025-05-29 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_habit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.task')),
            ],
            options={
                'unique_together': {('task', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='Habit',
        ),
    ]
