# Generated by Django 5.2 on 2025-05-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_subject_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
        migrations.AddField(
            model_name='topic',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
